import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/styles/globals.css';
import Navbar from "@/components/Navbar";
import Provider from "@/utils/Provider";
import TopLoader from "@/utils/top-loader";

import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import AuthProvider from "@/components/Core/AuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Restaran",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light" />
        <Provider>
          <TopLoader />
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
